name = "spinogambino-bet-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-bet.com.pt"
HMAC_KEY = "c3744b7cdf2e7db1d18814ecb74c54fa1634af35689ad1e5afa591531e7d4bd2"
COOKIE_NAME = "zmj"
PLAY_PATH = "visit-site"
BUTTON_ID = "p37dfad8f3207105d68ffd0a821bdda87"
GATE_SALT = "9261ae287e8e0598"
